<!-- Top level Directory.Build.props -->
<Project>

    <PropertyGroup>
        <!-- Compile and Build Settings -->
        <LangVersion>12</LangVersion>
        <Features>strict</Features>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisMode>Minimum</AnalysisMode>
		<!-- Common Package Versions -->
		<NUnitEngineApiVersion>4.0.0-beta.7</NUnitEngineApiVersion>
		<NUnitAgentCoreVersion>4.0.0-beta.5</NUnitAgentCoreVersion>
		<NUnitExtensibilityVersion>4.0.0-beta.3</NUnitExtensibilityVersion>
		<NUnitFrameworkVersion>4.1.0</NUnitFrameworkVersion>
	</PropertyGroup>

</Project>
