<!-- Top level Directory.Build.props -->
<Project>

    <PropertyGroup>
        <!-- Compile and Build Settings -->
        <LangVersion>12</LangVersion>
        <Features>strict</Features>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisMode>Minimum</AnalysisMode>
		<!-- Common Package Versions -->
		<NUnitEngineApiVersion>4.0.0-beta.2</NUnitEngineApiVersion>
		<NUnitAgentCoreVersion>4.0.0-beta.2</NUnitAgentCoreVersion>
	</PropertyGroup>

</Project>
